@php($editing = isset($note))
@php($selectedType = old('type', $editing ? $note->type : $type))
<form class="compose-form" x-data="{ words: 0 }" x-init="words = $refs.body.value.trim().split(/\s+/).filter(Boolean).length" @keydown.window="if (($event.metaKey || $event.ctrlKey) &amp;&amp; $event.key.toLowerCase() === 's') { $event.preventDefault(); $el.requestSubmit() }" method="POST" action="{{ $editing ? route('notes.update', $note) : route('notes.store') }}">
@csrf
@if($editing) @method('PATCH') @endif
@if($errors->any())<div class="notice" role="alert"><p>Please check the following:</p><ul class="list-disc pl-5 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="compose-grid"><div class="surface writing-canvas"><div class="canvas-chrome"><span aria-hidden="true">✎</span> Your note <span>Write → revisit → build</span></div><div class="canvas-content"><div class="mb-6"><label for="title" class="field-label">Title</label><input id="title" name="title" class="text-field w-full compose-title" value="{{ old('title', $editing ? $note->title : '') }}" placeholder="e.g. How Eloquent relationships work" maxlength="160" autofocus><p class="muted text-xs mt-2">A clear title makes this easier to find later.</p></div>
<label for="body" class="field-label">Your explanation</label><textarea x-ref="body" @input="words = $event.target.value.trim().split(/\s+/).filter(Boolean).length" id="body" name="body" rows="14" class="note-editor" placeholder="Explain it in your own words. What would help you next time?" maxlength="100000" required>{{ old('body', $editing ? $note->body : \App\Models\Note::TEMPLATES[$type]) }}</textarea>
<details class="code-details mt-6" @if(old('code', $editing ? $note->code : '')) open @endif><summary class="field-label cursor-pointer">Add a code example or command <span class="muted">(optional)</span></summary><label for="language" class="field-label mt-4">Language</label><select id="language" name="language" class="text-field mb-3">@foreach(['text' => 'Plain text', 'php' => 'PHP', 'javascript' => 'JavaScript', 'sql' => 'SQL', 'html' => 'HTML', 'css' => 'CSS', 'bash' => 'Shell', 'python' => 'Python', 'json' => 'JSON'] as $value => $label)<option value="{{ $value }}" @selected(old('language', $editing ? $note->language : 'text') === $value)>{{ $label }}</option>@endforeach</select><label for="code" class="sr-only">Code example</label><textarea class="code-editor" id="code" name="code" rows="7" spellcheck="false" maxlength="100000" placeholder="Paste the snippet or command you want to reuse.">{{ old('code', $editing ? $note->code : '') }}</textarea></details>
<div class="writing-count"><span x-text="words + ' words'"></span><span>⌘ / Ctrl + S to save</span></div></div></div><aside class="surface note-properties"><p class="eyebrow">Note properties</p><div class="form-columns mb-6"><div><label for="type" class="field-label">Note type</label><select id="type" name="type" class="text-field w-full">@foreach(\App\Models\Note::TYPES as $value => $label)<option value="{{ $value }}" @selected($selectedType === $value)>{{ $label }}</option>@endforeach</select></div><div><label for="notebook_id" class="field-label">Notebook</label><select id="notebook_id" name="notebook_id" class="text-field w-full"><option value="">Without a notebook</option>@foreach($notebooks as $notebook)<option value="{{ $notebook->id }}" @selected(old('notebook_id', $editing ? $note->notebook_id : '') == $notebook->id)>{{ $notebook->name }}</option>@endforeach</select><a class="text-link text-xs mt-2 inline-block" href="{{ route('notebooks.index') }}" target="_blank" rel="noopener">Create a notebook ↗</a></div></div>
<div class="mt-6"><label for="source_url" class="field-label">Source link <span class="muted">(optional)</span></label><input id="source_url" name="source_url" type="url" class="text-field w-full" value="{{ old('source_url', $editing ? $note->source_url : '') }}" placeholder="https://..." maxlength="2048"></div>
<fieldset class="tag-picker"><legend class="field-label">Tags <span class="muted font-normal">(optional)</span></legend>@if($tags->isNotEmpty())<div class="tag-options">@foreach($tags as $tag)<label class="tag-option"><input type="checkbox" name="tags[]" value="{{ $tag->id }}" @checked(in_array($tag->id, old('tags', $editing ? $note->tags->modelKeys() : [])))> {{ $tag->name }}</label>@endforeach</div>@else<p class="muted text-sm">No tags yet. <a class="text-link" href="{{ route('profile.edit') }}" target="_blank" rel="noopener">Create some in settings ↗</a></p>@endif</fieldset>
<div class="mt-6"><label for="status" class="field-label">Where are you with this?</label><select class="text-field w-full" name="status" id="status">@foreach(\App\Models\Note::STATUSES as $value => $label)<option value="{{ $value }}" @selected(old('status', $editing ? $note->status : 'learning') === $value)>{{ $label }}</option>@endforeach</select><p class="muted text-xs mt-2">Filter by “Still learning” in your notes to choose what to revisit.</p></div>
</aside></div><div class="form-footer"><a class="button-secondary" href="{{ $editing ? route('notes.show', $note) : route('notes.index') }}">Cancel</a><button class="button" type="submit">{{ $editing ? 'Save changes' : 'Save note' }}</button></div>
</form>
